import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageControls from "@/components/PageControls";
import { getTheme } from "./utils/change-theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getTheme();
  return (
    <html lang="en" className={`${theme}`}>
      <body className={inter.className}>
        <main className="grid grid-rows-[20fr,150px] w-screen h-screen">
          {children}
          <PageControls></PageControls>
        </main>
      </body>
    </html>
  );
}
